### ISSUE TITLE
Nits for adapter

### ISSUE THREAD

**Issue by flovilmart** [felixrieseberg/parse-server-azure-storage#1]
Hey there! Awesome work!

Just a quick thing, you don't need to inherit file adapter, we do prototype comparison to make sure the adapter implements the right methods.

I'm not familiar with `createBlockBlobFromText` but the data you receive is expected to be a Buffer. 
On the same note `getFileData` 's promise is supposedly resolving with a Buffer.

**Comment by felixrieseberg** [comment]
Thanks for the tips! `createBlockBlobFromText` accepts buffers (I admit, the naming isn't exactly transparent...), but I made sure that we return a buffer, too. Updated in `0.2.3` :bow:.

**Comment by flovilmart** [comment]
OK wonderful!
