### ISSUE TITLE
Blob Storage Setup

### ISSUE THREAD

**Issue by onosol** [felixrieseberg/parse-server-azure-storage#2]
I'm having issues saving a file with the Parse SDK from iOS. Can you provide details on how to create the storage container in Azure so I can verify my storage account and container are set up correctly. Thanks in advance!

**Comment by felixrieseberg** [comment]
Sure!
- Create a new Storage Account
- Create a new container (for instance named "parse")
- Click on the little key in the portal to get the access key
- Set the security policy to "blob"
- In your Parse server configuration, set `direct_access` to `true`

**Comment by onosol** [comment]
Ok, I'll give it another try. The only thing I didn't do was set direct_access to true. Does it only work if direct_access is true and the parse server is bypassed?

**Comment by felixrieseberg** [comment]
No, it should also work without just fine. If you ran into error, it'd be interesting to see the logs from your server - if you run your server on web apps, you can see them at YOURSITE.scm.azurewebsites.net.

**Comment by onosol** [comment]
Got it working! Thanks for the support. Can't wait for this to be merged into the official parse server repo.
