### ISSUE TITLE
How to use it from parse-server-example done by Azure ?

### ISSUE THREAD

**Issue by Sofianebenabdallah** [felixrieseberg/parse-server-azure-storage#3]
I have just installed parse server on Azure with the git https://github.com/Azure/parse-server-example

I want to use your adapter.

Regards

**Comment by felixrieseberg** [comment]
Change https://github.com/Azure/parse-server-example/blob/master/index.js - the example in [the readme](https://github.com/felixrieseberg/parse-server-azure-storage) should work.

**Comment by Sofianebenabdallah** [comment]
OK thank you for your feedback.

When do i need to do that : (I have Parse Server on Azure)

Then, install the adapter
npm install parse-server-azure-storage
Regards,

Sofiane

**Comment by felixrieseberg** [comment]
Hey, you can probably just wait for my colleagues to merge [the PR](https://github.com/Azure/parse-server-example/pull/5), but in the meantime, you can head over to Azure, run `npm install parse-server-azure` and configure your index.js to match the readme in this repo.

You can do those things either in Kudu (YOURSITE.scm.azurewebsites.net) or [using Visual Studio Online](https://blogs.msdn.microsoft.com/monaco/2014/06/25/how-to-access-visual-studio-online-monaco-from-the-new-azure-portal/). Thanks for trying it out!
