### ISSUE TITLE
npm: latest points at old version

### ISSUE THREAD

**Issue by craigpatten** [felixrieseberg/parse-server-azure-storage#7]
The `latest` tag for this package on [npm](https://www.npmjs.com/package/parse-server-azure-storage) refers to [0.3.1](https://github.com/felixrieseberg/parse-server-azure-storage/tree/0.3.1) (I'm guessing due to [publish](https://docs.npmjs.com/cli/publish) chronology) which is confusing given that we're up to [1.0.3](https://github.com/felixrieseberg/parse-server-azure-storage/tree/v1.0.3) now.

**Comment by felixrieseberg** [comment]
Yeah, good point. Let me quickly push an "update" so that people don't get confused.
