### ISSUE TITLE
Cannot uploaded File(image) with ParseAzureAdapter.

### ISSUE THREAD

**Issue by ghost** [felixrieseberg/parse-server-azure-storage#9]
I used this adpater, everytimes failed when uploading files.

[Take look these images.](https://1drv.ms/f/s!AjNep8R_zJV_p3SeDGgdAkyiYswk)

Can I solve this prob?

**Comment by ghost** [comment]
Azure technical team said 'blob' in _createBlobFromText property was empty, so It makes error.

**Comment by ghost** [comment]
```
@Override
    public void save() throws Exception {
        ParseObject object;
        if (getObjectId() != null) {
            object = ParseObject.createWithoutData(CLASS_NAME, getObjectId());
        } else {
            object = new ParseObject(CLASS_NAME);
        }

        if (header.getObjectId() == null) {
            header.setCreator(getCreatedBy());
            header.save();
        }
        object.put(KEY_HEADER, ParseObject.createWithoutData(TicketHeader.CLASS_NAME, header.getObjectId()));

        if (removeImageFlag) {
            object.remove(KEY_IMAGE);
        } else {
            if (newImageFile != null) {
                ParseFile file = new ParseFile(newImageFile);
                file.save();
                object.put(KEY_IMAGE, file);
            }
        }

        if (location != null) {
            if (location.getObjectId() == null) {
                location.setCreator(getCreatedBy());
                location.save();
            }
            object.put(KEY_LOCATION, ParseObject.createWithoutData(Location.CLASS_NAME, location.getObjectId()));
        }

        object.put(KEY_PRICE, price);
        object.put(KEY_DATE, date);

        ParseUser user = (ParseUser) ParseObject.createWithoutData("_User", createdBy.getObjectId());
        object.put(KEY_CREATED_BY, user);

        ParseACL acl = new ParseACL(user);
        acl.setPublicWriteAccess(false);
        acl.setPublicReadAccess(true);
        acl.setReadAccess(user, true);
        acl.setReadAccess(user, true);
        object.setACL(acl);

        object.save();
        setObjectId(object.getObjectId());
    }
```

Here is parts of code for saving ParseObject.

No selected file is okay.

**Comment by ghost** [comment]
Here is error logs :

> Error: **Parameter blob for function _createBlobFromText should be a non-empty string**
>     at ArgumentValidator._.extend.string (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/common/util/validate.js:431:13)
>     at /Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:4055:7
>     at Object.validateArgs (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/common/util/validate.js:498:3)
>     at BlobService._createBlobFromText (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:4053:12)
>     at BlobService.createBlockBlobFromText (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:2926:15)
>     at /Users/estylehq/TestServer/node_modules/parse-server-azure-storage/lib/AzureStorageAdapter.js:75:25
>     at /Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:497:7
>     at finalCallback (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:5037:7)
>     at /Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/common/services/storageserviceclient.js:832:11
>     at processResponseCallback (/Users/estylehq/TestServer/node_modules/parse-server-azure-storage/node_modules/azure-storage/lib/services/blob/blobservice.js:5040:5)

**Comment by ghost** [comment]
Okay. I solved my self.

Changed storage account type to blob, and azure dependency version (1.0.x).

**Comment by felixrieseberg** [comment]
Thanks for fixing it - I also updated this package with that fix!

**Comment by pknath** [comment]
@estylehq @felixrieseberg can you plz help me where to edit the  "Changed storage account type to blob"
I am getting the same error
